version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ebay-clone
    restart: unless-stopped
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: egoeimai7
      POSTGRES_DB: ebayclone
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: